apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8s-crds
spec:
  path: ./base/istio/k8s-gateway-crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ns
spec:
  path: ./base/istio/ns
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core
spec:
  path: ./base/istio/istio/base
  dependsOn:
    - name: ns
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: discovery
spec:
  path: ./base/istio/istio/istiod
  dependsOn:
    - name: core
    - name: k8s-crds
  postBuild:
    substitute:
      profile: ${profile}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cni
spec:
  path: ./base/istio/istio/cni
  dependsOn:
    - name: discovery
  postBuild:
    substitute:
      profile: ${profile}
      platform: ${platform}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ztunnel
spec:
  path: ./base/istio/istio/ztunnel
  dependsOn:
    - name: cni
  postBuild:
    substitute:
      profile: ${profile}
---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: istio-gw
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   retryInterval: 1m0s
#   path: ./base/istio/istio/gw
#   prune: true
#   wait: true
#   timeout: 2m0s
#   sourceRef:
#     kind: GitRepository
#     name: cluster-apps
#   dependsOn:
#     - name: istio-base
#     - name: istio-istiod
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: istio-resources
#   namespace: flux-system
# spec:
#   interval: 1m
#   path: ./base/istio/resources
#   prune: true
#   wait: true
#   timeout: 2m0s
#   sourceRef:
#     kind: GitRepository
#     name: cluster-apps
#   dependsOn:
#     - name: istio-gw
#   # postBuild:
#   #   substitute:
#   #     dns_name: ${dns_name}
