apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: release
spec:
  path: ./base/prometheus/release
  postBuild:
    substitute:
      domain: ${domain}
      cert_issuer_name: ${cert_issuer_name}
      route_prefix: ${route_prefix}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jobs
spec:
  path: ./base/prometheus/jobsConfigs
  dependsOn:
    - name: release
---
