apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secret-replicator
spec:
  interval: 5m
  targetNamespace: secret-replicator
  releaseName: secret-replicator
  chart:
    spec:
      chart: kubernetes-replicator
      version: 2.11.1
      sourceRef:
        kind: HelmRepository
        name: local-helm-repo
      interval: 1m
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #       - matchExpressions:
    #         - key: node.kubernetes.io/role
    #           operator: In
    #           values:
    #           - worker
    # tolerations:
    #   - key: "tenant"
    #     operator: "Equal"
    #     value: "workload"
    #     effect: "NoSchedule"

