apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-istiod
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: istio-system
  chart:
    spec:
      chart: istiod
      version: "1.25.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 1m
  values:
    profile: ${profile}
    pilot:
      cni:
        enabled: true
