apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
spec:
  interval: 5m
  targetNamespace: flagger-system
  releaseName: flagger
  chart:
    spec:
      chart: flagger
      version: 1.41.0
      sourceRef:
        kind: HelmRepository
        name: local-helm-repo
      interval: 1m
  install:
    crds: CreateReplace
    # createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    nodeSelector:
      kubernetes.io/os: linux  
    meshProvider: nginx
    metricsServer: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090${prometheus_route_prefix}
    podMonitor:
      enabled: true
      namespace: prometheus
      additionalLabels:
        release: prometheus

  #   namespace: istio-system
  #   crd:
  #     create: false

