apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: istio-ingress
  chart:
    spec:
      chart: gateway
      version: "1.25.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 1m
  # values:
  #   service:
  #     type: ClusterIP

