apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kiali-
namespace: flux-system

resources:
  - config.yaml

components:
  - ../../components/patches/default-ks-values
  - ../../components/configurations/rename-deps
  - ../../components/kube-auth-job

patches:
  - target:
      kind: Kustomization
      name: kubeauth-job
    patch: |
      - op: add
        path: /spec/dependsOn
        value:
          - name: kiali-namespace
