apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger-loadtester
spec:
  interval: 5m
  targetNamespace: flagger-lt
  releaseName: flagger-loadtester
  chart:
    spec:
      chart: loadtester
      version: 0.35.0
      sourceRef:
        kind: HelmRepository
        name: local-helm-repo
      interval: 1m
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace

