apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: istio-system
  chart:
    spec:
      chart: cni
      version: "1.25.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 1m
  values:
    global:
      platform: ${platform}
    profile: ${profile}


