apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
spec:
  interval: 5m
  targetNamespace: ${app_namespace}
  releaseName: kiali
  chart:
    spec:
      chart: kiali-server
      version: 2.x
      sourceRef:
        kind: HelmRepository
        name: local-helm-repo
      interval: 1m
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    auth:
      strategy: anonymous
    istio_namespace: istio-system
    deployment:
      # view_only_mode: true
      ingress:
        enabled: true
        override_yaml:
          metadata:
            annotations:
              cert-manager.io/cluster-issuer: ${cert_issuer_name}
              nginx.ingress.kubernetes.io/service-upstream: "true"
          spec:
            ingressClassName: nginx
            rules:
            - host: ${domain}
              http:
                paths:
                - backend:
                    service:
                      name: kiali
                      port:
                        number: 20001
                  path: /kiali
                  pathType: Prefix
            tls:
            - hosts:
              - ${domain}
              secretName: tls-cert
      server:
        web_port: 80
        web_schema: https
        web_root: /kiali
        web_fqdn: bede-apps.com
      custom_secrets:
      - name: "grafana-credentials"
        mount: "/kiali-override-secrets/grafana-credentials"

    external_services:
      custom_dashboards:
        enabled: true
      istio:
        root_namespace: istio-system
      tracing:
        enabled: false
      prometheus:
        url: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090${prometheus_route_prefix}
      grafana:
        url: http://grafana.grafana.svc.cluster.local:80/grafana
        internal_url: http://grafana.grafana.svc.cluster.local:80/grafana
        auth:
          type: basic
          enabled: true
          insecure_skip_verify: true
          username: "secret:grafana-credentials:grafana_user"
          password: "secret:grafana-credentials:grafana_password"