apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: release
spec:
  path: ./base/podinfo2/release
  postBuild:
    substitute:
      domain: ${domain}
      cert_issuer_name: ${cert_issuer_name}
