apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
spec:
  interval: 5m
  targetNamespace: ${nginx_namespace}
  releaseName: nginx-ingress
  chart:
    spec:
      chart: ingress-nginx
      version: 4.13.0
      sourceRef:
        kind: HelmRepository
        name: local-helm-repo
      interval: 1m
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    namespaceOverride: ${nginx_namespace}
    controller:
      allowSnippetAnnotations: "true"
      service:
        type: LoadBalancer
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          interval: 30s
          namespace: prometheus
          namespaceSelector:
            matchNames:
              - ${nginx_namespace}
          additionalLabels:
            release: prometheus
            
        traffic.sidecar.istio.io/includeInboundPorts: ""
        traffic.sidecar.istio.io/excludeInboundPorts: 80,443
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
    ingressClassResource:
      default: "true"
    commonLabels:
      shared-gateway-access: 'true'


