apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 5m
  targetNamespace: metallb-system
  chart:
    spec:
      chart: metallb
      version: 0.15.2
      sourceRef:
        kind: HelmRepository
        name: local-helm-repo
  values:
    # controller:
    #   affinity:
    #     nodeAffinity:
    #       requiredDuringSchedulingIgnoredDuringExecution:
    #         nodeSelectorTerms:
    #         - matchExpressions:
    #           - key: node.kubernetes.io/role
    #             operator: In
    #             values:
    #             - worker
    #   tolerations:
    #     - key: "tenant"
    #       operator: "Equal"
    #       value: "workload"
    #       effect: "NoSchedule"
    # speaker:
    #   affinity:
    #     nodeAffinity:
    #       requiredDuringSchedulingIgnoredDuringExecution:
    #         nodeSelectorTerms:
    #         - matchExpressions:
    #           - key: node.kubernetes.io/role
    #             operator: In
    #             values:
    #             - worker
    #   tolerations:
    #     - key: "tenant"
    #       operator: "Equal"
    #       value: "workload"
    #       effect: "NoSchedule"
    crds:
      validationFailurePolicy: Ignore
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace

