apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ztunnel
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: istio-system
  # releaseName: ztunnel
  chart:
    spec:
      chart: ztunnel
      version: "1.25.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 1m
  values:
    profile: ${profile}
    resourceName: ztunnel