apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo2
spec:
  interval: 5m
  targetNamespace: podinfo2
  releaseName: podinfo2
  chart:
    spec:
      chart: podinfo
      version: 6.8.0
      sourceRef:
        kind: HelmRepository
        name: local-helm-repo
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    ui:
      message: "Hello from Podinfo2"
      color: "#a86632"
    podAnnotations:
      app: podinfo2
      version: 5.0.0
    service:
      annotations:
        app: podinfo2
        version: 5.0.0
    replicaCount: 2
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 64Mi
    ingress:
      enabled: false
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: "/$2"
        cert-manager.io/cluster-issuer: ${cert_issuer_name}
        nginx.ingress.kubernetes.io/service-upstream: "true"
      hosts:
        - host: ${domain}
          paths:
            - path: "/podinfo2(/|$)(.*)"
              pathType: Prefix
      tls:
        - secretName: tls-cert
          hosts:
            - ${domain}

