# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
#   - group-config.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: nginx-ingress-
namespace: flux-system

resources:
  - config.yaml

components:
  - ../../components/patches/default-ks-values
  - ../../components/configurations/rename-deps