apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: cert-manager-
namespace: flux-system

resources:
  - config.yaml

components:
  - ../../components/patches/default-ks-values
  - ../../components/configurations/rename-deps
  - ../../components/kube-auth-job

patches:
  - path: kube-auth-job.patch.yaml
    target:
      kind: Kustomization
      name: kubeauth-job
  - target:
      kind: Kustomization
      name: kubeauth-job
    patch: |
      apiVersion: v1
      kind: all
      metadata:
        name: all
      spec:
        postBuild:
          substitute:
            k8s_audiences: ${k8s_audiences}

